/** Human-readable labels for llms.txt, RSS, and sitemaps. */
module.exports = {
  "/": "Home",
  "/about": "About KRIVA",
  "/contact": "Contact",
  "/process": "How we work",
  "/faq": "FAQ",
  "/privacy": "Privacy policy",
  "/terms": "Terms of service",
  "/technologies": "Tools & stack",
  "/services": "Services",
  "/solutions": "Solutions",
  "/work": "Case studies",
  "/insights": "Insights & guides",
  "/careers": "Careers",
  "/industries": "Industries",
  "/markets": "Markets we serve",
  "/markets/us": "United States",
  "/markets/uk": "United Kingdom",
  "/markets/uae": "United Arab Emirates",
  "/markets/ca": "Canada",
  "/solutions/trucking-logistics": "Trucking & logistics solutions",
  "/solutions/saas": "SaaS product solutions",
  "/solutions/accounting-integrations": "QuickBooks & Xero integrations",
  "/solutions/car-transportation": "Car transportation software",
  "/services/ai-assisted-development": "AI-assisted development",
  "/services/api-integrations": "API integrations",
  "/services/automation-systems": "Automation workflows",
  "/services/branding": "Branding",
  "/services/crm-development": "Dispatch CRM & TMS",
  "/services/dashboard-design": "Fleet dashboards",
  "/services/design-systems": "Design systems",
  "/services/graphic-design": "Graphic design",
  "/services/logo-design": "Logo design",
  "/services/mobile-applications": "Driver mobile apps",
  "/services/no-code-low-code": "No-code / low-code",
  "/services/product-design": "Product design & UX",
  "/services/saas-platforms": "SaaS product design",
  "/services/seo-digital-marketing": "SEO & digital marketing",
  "/services/ui-ux-design": "UI/UX design",
  "/services/ux-research": "UX research",
  "/services/web-application-design": "Web application design",
  "/services/web-development": "Web development",
  "/services/wireframing-prototyping": "Wireframing & prototyping",
  "/work/shiftrail-dispatch": "ShiftRail dispatch CRM",
  "/work/payroll-pro-saas": "PayrollPro SaaS",
  "/work/finance-sync-hub": "FinanceSync hub",
  "/work/healthtrack-mobile": "HealthTrack mobile",
  "/work/brandlift-ecommerce": "BrandLift ecommerce",
  "/work/crm-pulse-dashboard": "CRMPulse dashboard",
  "/work/ai-support-automation": "SupportAI automation",
  "/work/marketplace-mvp": "LocalServe marketplace MVP",
  "/insights/ai-in-product-design-2026": "AI in product design 2026",
  "/insights/saas-onboarding-patterns": "SaaS onboarding patterns",
  "/insights/saas-mvp-uk-guide": "SaaS MVP guide for UK startups",
  "/insights/no-code-vs-custom-mvp": "No-code vs custom MVP",
  "/insights/trucking-dispatch-crm-guide": "Dispatch CRM for US trucking",
  "/insights/crm-dashboard-ux-patterns": "CRM dashboard UX patterns",
  "/insights/choosing-a-digital-agency": "Choosing a digital agency",
};
